name: cicd-documentation

on:
  push:
      branches:
        - main
  pull_request:
      branches:
        - main
  workflow_dispatch:

jobs:
  run:
    name: 🚀 Run
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ✅ Run unit tests
        shell: bash
        run: |
          cd laboratories/cicd-documentation
          python3 -m unittest tree_test.py

      - name: 🚀 Run main.py
        shell: bash
        run: |
          cd laboratories/cicd-documentation
          python3 main.py
